AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: serverless-aws-lambda-custom-docker

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Parameters:
  Version:
    Type: String
    Default: '1.0.0'

  S3ConfigStackName:
    Description: Stack name which has all of the S3
    Type: String
    Default: s3-iam-config

Resources:
  MyCustomLambdaContainer:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: MyCustomLambdaContainer
      ImageUri: 878103297030.dkr.ecr.us-east-1.amazonaws.com/user_service:latest
      PackageType: Image
      Role:
        Fn::ImportValue: codebuild-AWS-Build-service-role
      AutoPublishAlias: live
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /user/all
            Method: get
